### ISSUE TITLE
Re-enable multiple tools files once Ansible 2.0 comes out

### ISSUE THREAD

**Issue by afgane** [galaxyproject/ansible-galaxy-tools#12]
PR #11 disabled use of multiple tools files (from PR #7) in exchange for interactive tool installation progress reporting. Ansible 2.0 will have support for `with_` directive in loops making it possible to add the multi-file support back in. Ansible 2.0 is [expected any day now](https://groups.google.com/forum/#!msg/ansible-project/E_rsN9oQA0M/DyGivo-s7xMJ).

**Comment by bgruening** [comment]
Sounds fantastic! Thanks @afgane and @mvdbeek.
I will update Docker to take advantage of this.

**Comment by nuwang** [comment]
Fixed by: https://github.com/galaxyproject/ansible-galaxy-tools/pull/23/commits/d3b08acc3e80724f96147fff957cae16c1965d87

**Comment by afgane** [comment]
Works nicely. Thanks.
