### ISSUE TITLE
Role finishes before all tools are installed

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/ansible-galaxy-tools#15]
This is not a big deal for running instances (since the install process will just continue), but when using this in a playbook that trigger a galaxy restart  or shutdown you get the remaining tools stuck in "new" or "installing dependencies" state.
This behaviour depends on the list of tools that you install, and happens mostly if at the end of the list you have something with a huge dependency chain (R packages are good candidates).
I'll have a look if we can use bioblend to check on the installation status.

**Comment by lecorguille** [comment]
I have the same behaviour.
My dirty solution is to install the "huge dependency chain" first and after the tools. But it will asked to check and update the list of tools with the lastest package version.

**Comment by mvdbeek** [comment]
A call to show_repositories (https://bioblend.readthedocs.org/en/latest/api_docs/galaxy/all.html#module-bioblend.galaxy.toolshed) should do it ... in fact we could even fail packages that had problems installing the dependencies. When driven to the extreme we could even use this in conjunction with travis to check if toolshed repositories install on OS X :)
I will do this now.

**Comment by afgane** [comment]
Are you thinking to change this https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/install_tool_shed_tools.py#L572 from checking that specific tool to keep checking all the repositories until they reach either `Installed` or `Error` status?

**Comment by mvdbeek** [comment]
well, initially I was not aware that this check is already in place.
It would be an option to check all repositories, indeed.
Better yet, galaxy should not return "Installed" before it's dependencies have not been installed / error-ed completely (I).

**Comment by afgane** [comment]
Galaxy not returning the `Installed` status message was the assumption under which this was written (at least, that's the experience I've seen via the UI) but if at least the two of you have run into this problem, I guess that's not necessarily the case. 
You want me to change this or are you already on it?

**Comment by mvdbeek** [comment]
Well, i would never refuse help :laughing: .
Though the circumstances in which this happens are not entirely clear to me.

**Comment by afgane** [comment]
Can you share your tools file so I can try to replicate the behavior?

**Comment by mvdbeek** [comment]
Sure, you can even get a docker image with the aborted install.
https://github.com/ARTbio/ansible-artimed/blob/metavisitor/extra-files/metavisitor_tool_list.yml
`docker run artbio/galaxy-kickstart-metavisitor-base`.
If you look into /home/galaxy/galaxy/uwsgi.log you see the shutdown of uwsgi while compiling freetype.

**Comment by mvdbeek** [comment]
@afgane I think I got it ...
at https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/install_tool_shed_tools.py#L559
you get the first item in the response (often a tool dependency), but the actual tool you requested is in the last item.
Changing response[0] to reponse[-1] should wait until the tool reports `Installed`.

**Comment by afgane** [comment]
Nice detective work! I did a check on this end as well and it looks like it's working.

Thank you.

**Comment by mvdbeek** [comment]
Thanks all!

**Comment by mvdbeek** [comment]
Well, extensive testing shows this is still a problem.
I'll see if we perhaps need to check for all items in response :/

**Comment by mvdbeek** [comment]
Okay, so the (next) problem is an nginx timeout. Catching the 504 and re-trying seems to work.

**Comment by mvdbeek** [comment]
@afgane @lecorguille 
This is solved with PR #17 .
To make this more smooth I opened an [issue](https://github.com/galaxyproject/galaxy/issues/1628) on galaxy.
