### ISSUE TITLE
Modulize the installation script

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/ansible-galaxy-tools#2]
The script is useful as a standalone script, so it's probably not necessary to fully convert it to a module, but a simple module that acts as a wrapper around the install script would make this a bit more Ansibley - that would take care of copying it over and running it for you, and cleaning up afterward. It also means you could have correct reporting of the `changed` status.

That said, it's actually not necessary to copy it over at all. It could run on the host from which you're running Ansible.

**Comment by natefoo** [comment]
I see in `tools.yml` that it in fact does run locally. Heh.

**Comment by natefoo** [comment]
I am a little wary of using this on Galaxy Main for the moment just because I won't be able to tell individually what it did. If Ansible itself read the tool YAML and provided that to a tool installation module as `{{ item }}`s you'd get a single line of output showing changed or unchanged for each item in the tool list. Which would be awesome.

**Comment by afgane** [comment]
That's a good idea. I'll see how to make it happen. 

For what it's worth, it logs to `/tmp/galaxy_tool_install.log` where is captures everything that's done.
