### ISSUE TITLE
manage_bootstrap_user.py doesn't delete user

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/ansible-galaxy-tools#22]
Hi there,
I've been using the manage bootstrap user scripts for a while to install tools etc in my Galaxy setups. However, I've noticed that:

_manage_bootstrap_user.py delete -u username_  doesn't work. It leaves the user in the database...

The delete function being called from `__main__` :

```
def delete_bootstrap_user(ini_file, username):
    app = get_bootstrap_app(ini_file)
    user = delete_user(app, username)
    if user is not None:
        exit(0)
    else:
        log.error("Problem deleting user: {0}".format(username))
        exit(1)
```

There is another function called _delete_user_ which looks as though it will delete the user from the postgres database but doesn't seem to work.

```
def delete_user(app, username):
    user = app.sa_session.query(app.model.User).filter(
        app.model.User.table.c.username == username).first()
    app.sa_session.delete(user)
    app.sa_session.flush()
    return user
```

Cheers,

Simon.

**Comment by nuwang** [comment]
It's calling the delete user function and checking the return value to see
whether it's null right? So the function does indeed get invoked before the
null test - so it looks like the delete_user function is faulty?

**Comment by Slugger70** [comment]
Oh yeah. Of course it is. But it's also not removing the user from the galaxy.ini file
