### ISSUE TITLE
Do not report sucess when tool_list.yml does not conform

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/ansible-galaxy-tools#24]
When tool_panel_section_label and tool_panel_section_id are missing from the tool_list.yml entries, ansible reports successful installation, when actually nothing has happened.
Since this might be something users would try if they want to have the tools outside of any section,
I guess we should either fail or add a default tool_panel_section_id ("no_tool_panel_section_id").
Any opinions on that issue, @bgruening @afgane @nuwang ?

**Comment by bgruening** [comment]
+1 for failing

**Comment by nuwang** [comment]
+1 for failing from me too. (Assuming there's a way to specify a default section without this)

**Comment by afgane** [comment]
Should be resolved now.

**Comment by mvdbeek** [comment]
Awesome, thanks @afgane
