### ISSUE TITLE
This as a library?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/ansible-galaxy-tools#28]
Planemo now has a profiles feature - allowing persistent little environments for using commands like `serve`, `shed_serve`, `test`, and `shed_test`. This would be nice for tool development (consistent histories across `serve`s) but is almost essential for workflow development. It needs to be possible to quickly get back to a Galaxy with a set of shed tools installed for instance.

So I'd like to implement `--tool_list <path/to/tools.yml>`, `--data_list <path/to/data.yml>`, and `--workflow_list <path/to/workflows.yml>` and I'd like to leverage what is here I think. There are three clear paths to do this without me just copying and pasting everything:
1. Planemo could add a dependency on ansible and run the role directly. The role would be included into `planemo_ext` I guess as a submodule.
2. The scripts could be placed onto PyPI as a new project and I could skip ansible but use the scripts as a library.
3. The scripts could be moved into planemo and then this role could have a dependency on planemo - again Planemo would use the scripts as a library and skip ansible.

Does anyone have any thoughts on using this as library or within planemo specifically?

(1) seems like it would be the most work for me right now and could potentially not gel well with what I am doing with planemo - on the other-hand it might setup a bunch of infrastructure within planemo that allows it to do some really cool things down the road. Seems the riskiest route - high risk, high reward potential.

(3) Would add a significant dependency for users of this project - but it would give these scripts a nice home that would probably lead to increased testing, linting, Python 3 support, etc.... I'm not sure what I would loose using the scripts directly instead of through ansible when using this as a library - any thoughts on this?

(2) seems like it would be the least disruptive - it would improve this project a little, the scripts a little, and would help planemo. We'd have to come up with a name for the scripts though and that is always stressful.

Ping @afgane @mvdbeek @bgruening

**Comment by mvdbeek** [comment]
Well, from the feedback so far on the mailing list and github, I'd say people trying to use the tool installation functionality struggle with ansible, so from that perspective option 2 and 3 provide a clear path of improvement.

I think I'd go with option 3, since you're doing an awesome job with planemo ;).
We could easily adopt planemo in this role, if for example there was a command

```
planemo shed_install <tool_list.yml>
```

I think the galaxy ecosystem is already quite complex, so having an all around planemo tool/workflow sdk makes more sense to me as compared to having another package for getting your tool list installed.

**Comment by martenson** [comment]
Ideally this would be `galaxy tool_install <tool_list.yml>`, right? Not that Galaxy needs a CLI but Galaxy should know (and provide interface to) how to install a list of tools.

IOW Admin API should contain an endpoint that accept yaml/json list of tools and installs them all. Is that naive?

**Comment by bgruening** [comment]
:+1: for option 2. I always felt that package on pypi/conda would be great and the easiest way for many users. This role can simply install this package.
