### ISSUE TITLE
install_tool_shed_tools.py does not work with testtoolshed ?

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/ansible-galaxy-tools#30]
Installation from toolshed works:

```
(.venv)root@vm0040:~/ansible-artimed/roles/galaxyprojectdotorg.galaxy-tools/files# python install_tool_shed_tools.py -g http://192.54.201.71/ -a d5c6ca76721721742742e8f8051f7e68 --name fetch_fasta_from_ncbi --owner drosofff --section RNAseq --toolshed https://toolshed.g2.bx.psu.edu/
(1/1) Installing tool fetch_fasta_from_ncbi from drosofff to section "RNAseq" at revision befdb392fece (TRT: 0:00:00.635433)
    Tool fetch_fasta_from_ncbi installed successfully (in 0:00:06.031311) at revision befdb392fece
Installed tools (1): [('fetch_fasta_from_ncbi', u'befdb392fece')]
Skipped tools (0): []
Errored tools (0): []
All tools listed in 'None' have been processed.
Total run time: 0:00:06.667989
```

but the example given in the help section of the tool does not:

```
(.venv)root@vm0040:~/ansible-artimed/roles/galaxyprojectdotorg.galaxy-tools/files# python install_tool_shed_tools.py -g http://192.54.201.71/ -a d5c6ca76721721742742e8f8051f7e68 --yaml_tool "{'owner': 'kellrott', 'tool_shed_url': 'https://testtoolshed.g2.bx.psu.edu', 'tool_panel_section_id': 'peak_calling', 'name': 'synapse_interface'}"
(1/1) Installing tool synapse_interface from kellrott to section "peak_calling" at revision 3dcbc98040a1 (TRT: 0:00:00.807190)
    * Error installing a tool (after synapse_interface)! Name: 0:00:00.523945,owner: kellrott, revision: 3dcbc98040a1, error: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
Installed tools (0): []
Skipped tools (0): []
Errored tools (1): [('synapse_interface', u'3dcbc98040a1')]
All tools listed in 'None' have been processed.
Total run time: 0:00:01.331707
```

Also tested without success using a yml file, or parameters supplied in the command line.

**Comment by bgruening** [comment]
@drosofff please make sure you have activated the TestToolShed. Since a few Galaxy releases the TTS is deactiavated and you can not install from it by default.

**Comment by drosofff** [comment]
@bgruening you're right, my manual activation of the testtoolshed in the conf file was reverted by the ansible playbook. Thanks.

Thus my question becomes:
what is the simplest way to overwrite https://github.com/galaxyproject/ansible-galaxy/blob/0f78dde618c3d6105859875b0e45e6c74e673e09/defaults/main.yml#L63 so that using ansible-playbook the tool_sheds_conf.xml.sample file gets the testtoolshed info uncommented ?

Sorry Bjorn, you may not be the person who has to think to this. ping @mvdbeek ?

**Comment by bgruening** [comment]
You know one community :)
This is how I do it in the Galaxy container: https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/templates/startup.sh.j2#L21 but it means you need to ship an alternative `tool_sheds_conf.xml`. Not sure if this exists in your setup. This is more for changing during runtime, not build-time.

**Comment by drosofff** [comment]
Thanks @bgruening I'll consider shipping an alternative tool_sheds_conf.xml in the extra files of the playbook

**Comment by bgruening** [comment]
An alternative would be t use the ansible.xml module: https://github.com/cmprescott/ansible-xml
But this is not in core and for myself I found the extra file more convenient.

**Comment by afgane** [comment]
Independent of this issue, I had updated the sample tool file to not use the TestToolShed (in https://github.com/galaxyproject/ansible-galaxy-tools/commit/7829517110b2f5a8dbd3e272e86b3b4494ead861) so consequently the script should now work out of the box with a fresh installation of Galaxy, which is probably the desirable behavior.

So, should we close this issue or is there something better that should be done?

**Comment by drosofff** [comment]
It's OK for me. Thanks @bgruening & @afgane

**Comment by bgruening** [comment]
Thanks @drosofff!
