### ISSUE TITLE
tool_panel_section_label isn't working, nor is tool_panel_section_id

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/ansible-galaxy-tools#35]

**Comment by mvdbeek** [comment]
Please make sure you are using the latest version.
If there is a problem, please first report using ephemeris.
You can get ephemeris through `pip install ephemeris`.

**Comment by alexlenail** [comment]
This is using @bgruening's latest image -- perhaps I should report it there?

**Comment by mvdbeek** [comment]
We are aware of this. I'll try to get it out today. Thanks @zfrenchee

**Comment by alexlenail** [comment]
@mvdbeek I lied -- tool_panel_section_id doesn't work either! What's the plan for fixing it? Will this fix make it into the docker image today?

**Comment by alexlenail** [comment]
@mvdbeek What's the status on this?

**Comment by mvdbeek** [comment]
https://github.com/bgruening/docker-galaxy-stable/pull/233
