### ISSUE TITLE
urlopen error [Errno 104] Connection reset by peer>", "err_code": 500001

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/ansible-galaxy-tools#36]
My [galaxy flavor](https://github.com/fraenkel-lab/galaxy-neurolincs) installs 26 tools. One of the installs fails: 

```
(11/26) Installing tool rgrnastar from iuc to section "RNAseq" at revision ace9f5a2b40f (TRT: 0:42:06.345389)
        * Error installing a tool (after 0:07:06.264252 seconds)! Name: rgrnastar,owner: iuc, revision: ace9f5a2b40f, error: {"err_msg": "Error attempting to retrieve installation information from tool shed https://toolshed.g2.bx.psu.edu/ for revision ace9f5a2b40f of repository rgrnastar owned by iuc: <urlopen error [Errno 104] Connection reset by peer>", "err_code": 500001}
```

What is this error?

**Comment by storeman** [comment]
Same here. When installing the required roles for my own project I got the same error "[Errno 104] Connection reset by peer". Seems to be some kind of issue with Ansible Galaxy.

When I try it several times with different settings it will eventually come through succesfully. I think it has got something to do with the Ansible Galaxy API and SSL. When installing roles with `ansible-galaxy install -r myroles.yml` adding the `-vvv`  parameter seems to fix the issue sometimes. Also when installing seperate roles with the `-vvv` parameter seems to continue sometimes.

**Comment by mvdbeek** [comment]
These are different issues, and I think @storeman you may want to report this at https://github.com/ansible/ansible. This here is a repository containing ansible roles for the [galaxy](https://usegalaxy.org) bioinformatics server, which is not related to ansible galaxy.

In general, `connection reset by peer` points to connectivity issues https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean.
