### ISSUE TITLE
manage_bootstrap_user.py command line parsing

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/ansible-galaxy-tools#39]
The command line parser in manage_bootstrap_user.py uses 

required="false" and required="true" 

which should be 

required=False and required=True

Thanks

**Comment by nuwang** [comment]
Fixed in commit: https://github.com/galaxyproject/ansible-galaxy-tools/commit/5b1326e487bc8c4f3b22fa5d64743e475bd04600
